# Generated by Django 3.2 on 2022-02-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservedTime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
