# Generated by Django 4.0.2 on 2022-02-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
